AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template deploys an S3 Bucket into the provisioning Account without Encryption'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
Outputs:
  S3BucketName:
    Value: !GetAtt S3Bucket.Arn
